name: Update PWHL Data

on:
  schedule:
    # PWHL regular season: November through March
    - cron: '0 9 * 11-12 *'
    - cron: '0 9 * 1-3 *'
    # Playoffs: March through May
    - cron: '0 9 * 4-5 *'
  repository_dispatch:
    types: [daily_pwhl_data]
  workflow_dispatch:
    inputs:
      start_year:
        description: 'Start year (e.g. 2025 for 2024-25 season)'
        required: false
        type: string
      end_year:
        description: 'End year (e.g. 2025 for 2024-25 season)'
        required: false
        type: string

jobs:
  update_pwhl_data:
    runs-on: ${{ matrix.config.os }}
    name: Update PWHL Data ${{ inputs.start_year }}-${{ inputs.end_year }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: 'ubuntu-latest', r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      START_YEAR: ${{ inputs.start_year }}
      END_YEAR: ${{ inputs.end_year }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setting up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Setting up R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 1
          extra-packages: |
            sportsdataverse/fastRhockey
            sportsdataverse/sportsdataverse-data
            ropensci/piggyback

      - name: Check fastRhockey_pwhl_data_trigger for inputs
        if: ${{ github.event.client_payload.event_name == 'daily_pwhl_data' }}
        run: |
          echo START_YEAR=$(echo "${{ github.event.client_payload.commit_message }}" | grep -o -E '[0-9]+' | head -1) >> $GITHUB_ENV
          echo END_YEAR=$(echo "${{ github.event.client_payload.commit_message }}" | grep -o -E '[0-9]+' | tail -1) >> $GITHUB_ENV

      - name: Check for empty inputs
        if: ${{ env.START_YEAR == '' }}
        run: |
          echo START_YEAR=$(Rscript -e "cat(fastRhockey:::most_recent_pwhl_season())") >> $GITHUB_ENV
          echo END_YEAR=$(Rscript -e "cat(fastRhockey:::most_recent_pwhl_season())") >> $GITHUB_ENV

      - name: Update PWHL Data ${{ env.START_YEAR }}-${{ env.END_YEAR }}
        env:
          GITHUB_PAT: ${{ secrets.SDV_GH_TOKEN }}
        run: |
          bash scripts/daily_pwhl_R_processor.sh -s ${{ env.START_YEAR }} -e ${{ env.END_YEAR }}
